version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginxserver
    restart: always
    ports:
      - "80:80"
    build:
        context: ./nginx
        dockerfile: Dockerfile
    depends_on:
      - backend
    network_mode: host
    environment:
      - TZ=Asia/Seoul
  backend:
    image: ${DOCKERHUB_USERNAME}/infra_practice_server:latest
    container_name: deploy_container
    restart: always
    expose:
      - "8080"
    network_mode: host
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
